/*
 * EXTI.h
 *
 *  Created on: Aug 31, 2022
 *      Author: AM
 */

#ifndef INC_EXTI_H_
#define INC_EXTI_H_

#include "STM32f103c6_GPIO.h"

typedef struct{
	uint8_t 			Pin_number;
	uint8_t				EXTI_Line_Num;
	GPIO_TypeDef* 		GPIOx;
	uint8_t				IRQ_Num;
}EXTI_GPIO_Mapping_t;

typedef struct{
	EXTI_GPIO_Mapping_t EXTI_pin;									//This parameter specifies the pin mapping
																	//This parameter should be set based on values @EXTI_pin
	uint8_t				Edge_trigger;								//This parameter specifies the edge trigger detection
																	//This parameter should be set based on values @EXTI_Edge_trigger
	void(*P_IRQ_Callback)(void) ;									//This parameter specifies a pointer to be executed during interrupt
}EXTI_Pin_Cfg_t;


#define EXTI_0	0
#define EXTI_1	1
#define EXTI_2	2
#define EXTI_3	3
#define EXTI_4	4
#define EXTI_5	5
#define EXTI_6	6
#define EXTI_7	7
#define EXTI_8	8
#define EXTI_9	9
#define EXTI_10	10
#define EXTI_11	11
#define EXTI_12	12
#define EXTI_13	13
#define EXTI_14	14
#define EXTI_15	15

//@EXTI_pin

///EXTI0
#define EXTI0_PA0	(EXTI_GPIO_Mapping_t){GPIO_PIN_0,EXTI_0,GPIO_PORTA,EXTI0_IRQn}
#define EXTI0_PB0	(EXTI_GPIO_Mapping_t){GPIO_PIN_0,EXTI_0,GPIO_PORTB,EXTI0_IRQn}
#define EXTI0_PC0	(EXTI_GPIO_Mapping_t){GPIO_PIN_0,EXTI_0,GPIO_PORTC,EXTI0_IRQn}
#define EXTI0_PD0	(EXTI_GPIO_Mapping_t){GPIO_PIN_0,EXTI_0,GPIO_PORTD,EXTI0_IRQn}



///EXTI1
#define EXTI1_PA1	(EXTI_GPIO_Mapping_t){GPIO_PIN_1,EXTI_1,GPIO_PORTA,EXTI1_IRQn}
#define EXTI1_PB1	(EXTI_GPIO_Mapping_t){GPIO_PIN_1,EXTI_1,GPIO_PORTB,EXTI1_IRQn}
#define EXTI1_PC1	(EXTI_GPIO_Mapping_t){GPIO_PIN_1,EXTI_1,GPIO_PORTC,EXTI1_IRQn}
#define EXTI1_PD1	(EXTI_GPIO_Mapping_t){GPIO_PIN_1,EXTI_1,GPIO_PORTD,EXTI1_IRQn}



///EXTI2
#define EXTI2_PA2	(EXTI_GPIO_Mapping_t){GPIO_PIN_2,EXTI_2,GPIO_PORTA,EXTI2_IRQn}
#define EXTI2_PB2	(EXTI_GPIO_Mapping_t){GPIO_PIN_2,EXTI_2,GPIO_PORTB,EXTI2_IRQn}
#define EXTI2_PC2	(EXTI_GPIO_Mapping_t){GPIO_PIN_2,EXTI_2,GPIO_PORTC,EXTI2_IRQn}
#define EXTI2_PD2	(EXTI_GPIO_Mapping_t){GPIO_PIN_2,EXTI_2,GPIO_PORTD,EXTI2_IRQn}



///EXTI3
#define EXTI3_PA3	(EXTI_GPIO_Mapping_t){GPIO_PIN_3,EXTI_3,GPIO_PORTA,EXTI3_IRQn}
#define EXTI3_PB3	(EXTI_GPIO_Mapping_t){GPIO_PIN_3,EXTI_3,GPIO_PORTB,EXTI3_IRQn}
#define EXTI3_PC3	(EXTI_GPIO_Mapping_t){GPIO_PIN_3,EXTI_3,GPIO_PORTC,EXTI3_IRQn}
#define EXTI3_PD3	(EXTI_GPIO_Mapping_t){GPIO_PIN_3,EXTI_3,GPIO_PORTD,EXTI3_IRQn}



///EXTI4
#define EXTI4_PA4	(EXTI_GPIO_Mapping_t){GPIO_PIN_4,EXTI_4,GPIO_PORTA,EXTI4_IRQn}
#define EXTI4_PB4	(EXTI_GPIO_Mapping_t){GPIO_PIN_4,EXTI_4,GPIO_PORTB,EXTI4_IRQn}
#define EXTI4_PC4	(EXTI_GPIO_Mapping_t){GPIO_PIN_4,EXTI_4,GPIO_PORTC,EXTI4_IRQn}
#define EXTI4_PD4	(EXTI_GPIO_Mapping_t){GPIO_PIN_4,EXTI_4,GPIO_PORTD,EXTI4_IRQn}



///EXTI5
#define EXTI5_PA5	(EXTI_GPIO_Mapping_t){GPIO_PIN_5,EXTI_5,GPIO_PORTA,EXTI5_IRQn}
#define EXTI5_PB5	(EXTI_GPIO_Mapping_t){GPIO_PIN_5,EXTI_5,GPIO_PORTB,EXTI5_IRQn}
#define EXTI5_PC5	(EXTI_GPIO_Mapping_t){GPIO_PIN_5,EXTI_5,GPIO_PORTC,EXTI5_IRQn}
#define EXTI5_PD5	(EXTI_GPIO_Mapping_t){GPIO_PIN_5,EXTI_5,GPIO_PORTD,EXTI5_IRQn}



///EXTI6
#define EXTI6_PA6	(EXTI_GPIO_Mapping_t){GPIO_PIN_6,EXTI_6,GPIO_PORTA,EXTI6_IRQn}
#define EXTI6_PB6	(EXTI_GPIO_Mapping_t){GPIO_PIN_6,EXTI_6,GPIO_PORTB,EXTI6_IRQn}
#define EXTI6_PC6	(EXTI_GPIO_Mapping_t){GPIO_PIN_6,EXTI_6,GPIO_PORTC,EXTI6_IRQn}
#define EXTI6_PD6	(EXTI_GPIO_Mapping_t){GPIO_PIN_6,EXTI_6,GPIO_PORTD,EXTI6_IRQn}



///EXTI7
#define EXTI7_PA7	(EXTI_GPIO_Mapping_t){GPIO_PIN_7,EXTI_7,GPIO_PORTA,EXTI7_IRQn}
#define EXTI7_PB7	(EXTI_GPIO_Mapping_t){GPIO_PIN_7,EXTI_7,GPIO_PORTB,EXTI7_IRQn}
#define EXTI7_PC7	(EXTI_GPIO_Mapping_t){GPIO_PIN_7,EXTI_7,GPIO_PORTC,EXTI7_IRQn}
#define EXTI7_PD7	(EXTI_GPIO_Mapping_t){GPIO_PIN_7,EXTI_7,GPIO_PORTD,EXTI7_IRQn}



///EXTI8
#define EXTI8_PA8	(EXTI_GPIO_Mapping_t){GPIO_PIN_8,EXTI_8,GPIO_PORTA,EXTI8_IRQn}
#define EXTI8_PB8	(EXTI_GPIO_Mapping_t){GPIO_PIN_8,EXTI_8,GPIO_PORTB,EXTI8_IRQn}
#define EXTI8_PC8	(EXTI_GPIO_Mapping_t){GPIO_PIN_8,EXTI_8,GPIO_PORTC,EXTI8_IRQn}
#define EXTI8_PD8	(EXTI_GPIO_Mapping_t){GPIO_PIN_8,EXTI_8,GPIO_PORTD,EXTI8_IRQn}



///EXTI9
#define EXTI9_PA9	(EXTI_GPIO_Mapping_t){GPIO_PIN_9,EXTI_9,GPIO_PORTA,EXTI9_IRQn}
#define EXTI9_PB9	(EXTI_GPIO_Mapping_t){GPIO_PIN_9,EXTI_9,GPIO_PORTB,EXTI9_IRQn}
#define EXTI9_PC9	(EXTI_GPIO_Mapping_t){GPIO_PIN_9,EXTI_9,GPIO_PORTC,EXTI9_IRQn}
#define EXTI9_PD9	(EXTI_GPIO_Mapping_t){GPIO_PIN_9,EXTI_9,GPIO_PORTD,EXTI9_IRQn}



///EXTI10
#define EXTI10_PA10	(EXTI_GPIO_Mapping_t){GPIO_PIN_10,EXTI_10,GPIO_PORTA,EXTI10_IRQn}
#define EXTI10_PB10	(EXTI_GPIO_Mapping_t){GPIO_PIN_10,EXTI_10,GPIO_PORTB,EXTI10_IRQn}
#define EXTI10_PC10	(EXTI_GPIO_Mapping_t){GPIO_PIN_10,EXTI_10,GPIO_PORTC,EXTI10_IRQn}
#define EXTI10_PD10	(EXTI_GPIO_Mapping_t){GPIO_PIN_10,EXTI_10,GPIO_PORTD,EXTI10_IRQn}



///EXTI11
#define EXTI11_PA11	(EXTI_GPIO_Mapping_t){GPIO_PIN_11,EXTI_11,GPIO_PORTA,EXTI11_IRQn}
#define EXTI11_PB11	(EXTI_GPIO_Mapping_t){GPIO_PIN_11,EXTI_11,GPIO_PORTB,EXTI11_IRQn}
#define EXTI11_PC11	(EXTI_GPIO_Mapping_t){GPIO_PIN_11,EXTI_11,GPIO_PORTC,EXTI11_IRQn}
#define EXTI11_PD11	(EXTI_GPIO_Mapping_t){GPIO_PIN_11,EXTI_11,GPIO_PORTD,EXTI11_IRQn}



///EXTI12
#define EXTI12_PA12	(EXTI_GPIO_Mapping_t){GPIO_PIN_12,EXTI_12,GPIO_PORTA,EXTI12_IRQn}
#define EXTI12_PB12	(EXTI_GPIO_Mapping_t){GPIO_PIN_12,EXTI_12,GPIO_PORTB,EXTI12_IRQn}
#define EXTI12_PC12	(EXTI_GPIO_Mapping_t){GPIO_PIN_12,EXTI_12,GPIO_PORTC,EXTI12_IRQn}
#define EXTI12_PD12	(EXTI_GPIO_Mapping_t){GPIO_PIN_12,EXTI_12,GPIO_PORTD,EXTI12_IRQn}



///EXTI13
#define EXTI13_PA13	(EXTI_GPIO_Mapping_t){GPIO_PIN_13,EXTI_13,GPIO_PORTA,EXTI13_IRQn}
#define EXTI13_PB13	(EXTI_GPIO_Mapping_t){GPIO_PIN_13,EXTI_13,GPIO_PORTB,EXTI13_IRQn}
#define EXTI13_PC13	(EXTI_GPIO_Mapping_t){GPIO_PIN_13,EXTI_13,GPIO_PORTC,EXTI13_IRQn}
#define EXTI13_PD13	(EXTI_GPIO_Mapping_t){GPIO_PIN_13,EXTI_13,GPIO_PORTD,EXTI13_IRQn}



///EXTI14
#define EXTI14_PA14	(EXTI_GPIO_Mapping_t){GPIO_PIN_14,EXTI_14,GPIO_PORTA,EXTI14_IRQn}
#define EXTI14_PB14	(EXTI_GPIO_Mapping_t){GPIO_PIN_14,EXTI_14,GPIO_PORTB,EXTI14_IRQn}
#define EXTI14_PC14	(EXTI_GPIO_Mapping_t){GPIO_PIN_14,EXTI_14,GPIO_PORTC,EXTI14_IRQn}
#define EXTI14_PD14	(EXTI_GPIO_Mapping_t){GPIO_PIN_14,EXTI_14,GPIO_PORTD,EXTI14_IRQn}



///EXTI15
#define EXTI15_PA15	(EXTI_GPIO_Mapping_t){GPIO_PIN_15,EXTI_15,GPIO_PORTA,EXTI15_IRQn}
#define EXTI15_PB15	(EXTI_GPIO_Mapping_t){GPIO_PIN_15,EXTI_15,GPIO_PORTB,EXTI15_IRQn}
#define EXTI15_PC15	(EXTI_GPIO_Mapping_t){GPIO_PIN_15,EXTI_15,GPIO_PORTC,EXTI15_IRQn}
#define EXTI15_PD15	(EXTI_GPIO_Mapping_t){GPIO_PIN_15,EXTI_15,GPIO_PORTD,EXTI15_IRQn}


//@EXTI_Edge_trigger
#define RISING_EDGE_TRIGGER			0
#define FALLING_EDGE_TRIGGER		1
#define RISING_FALLING_EDGE_TRIGGER	2

void EXTI_GPIO_Inite(EXTI_Pin_Cfg_t* EXTI_Cfg);
void EXTI_GPIO_DeInite(EXTI_GPIO_Mapping_t* EXTI_Cfg);
void EXTI_GPIO_Update(EXTI_Pin_Cfg_t* EXTI_Cfg);


#endif /* INC_EXTI_H_ */
