/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "EXTI.h"
uint8_t flag=4;//possible values @ref flag values
void fun_0(void)
{
	MCAL_GPIO_TogglePin(GPIO_PORTB,GPIO_PIN_0);
	if (flag==3)flag=2;			//check if the previous configuration is FALLING_EDGE_TRIGGER
	else if(flag==4)flag=1;		//check if the previous configuration is RISING_EDGE_TRIGGER
}
int main(void)
{
	RCC_GPIO_PORTA_CLK_EN();
	RCC_GPIO_PORTB_CLK_EN();
	RCC_AFIO_CLK_EN();
	GPIO_pin_configue_t PB0;
	PB0.GPIO_pin_number=GPIO_PIN_0;
	PB0.GPIO_pin_mode=GPIO_MODE_OUTPUT_10M;
	PB0.GPIO_pin_CNF=GPIO_OUT_PUSHPULL;
	MCAL_GPIO_Init(GPIO_PORTB,&PB0);

	EXTI_Pin_Cfg_t test;
	test.EXTI_pin=EXTI1_PB1;
	test.Edge_trigger=RISING_EDGE_TRIGGER;
	test.P_IRQ_Callback=fun_0;
	EXTI_GPIO_Inite(&test);

	/* Loop forever */
	while(1)
	{
		if(flag==1)
		{
			test.Edge_trigger=FALLING_EDGE_TRIGGER;
			flag=3;
			EXTI_GPIO_Update(&test);
		}
		else if(flag==2)
		{
			test.Edge_trigger=RISING_EDGE_TRIGGER;
			EXTI_GPIO_Update(&test);
			flag=4;
		}

	}
}


//@ref flag values            //flag=1,2 are used in while(1)
							  //flag=3,4 are used in the interrupt handler
//flag=1 means the previous interrupt handler is executed due to falling edge trigger
//flag=2 means the previous interrupt handler is executed due to rising edge trigger
//flag=3 means the interrupt handler just execute the the falling edge trigger interrupt
//flag=4 means the interrupt handler just execute the the rising edge trigger interrupt

