/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "GPIO.h"
//RCC register address




void GPIOA_init()
{
	//enable GPIOA clock
	RCC_APB2ENR|=(1<<2);
	//enable GPIOB clock
	RCC_APB2ENR|=(1<<3);
	//configure PA 1 as an input high impedance
	GPIOA_CRL&=0xFFFFFF0F;
	GPIOA_CRL|=(1<<6);
	//configure PA 13 as an input high impedance
	GPIOA_CRH&=0xFF0FFFFF;
	GPIOA_CRH|=1<<22;
	//configure pin PB1 as an output push pull
	GPIOB_CRL&=0xFFFFFF0F;
	GPIOB_CRL|=(1<<4);
	//configure PB13 as an output push pull
	GPIOB_CRH&=0xFF0FFFFF;
	GPIOB_CRH|=(1<<20);
}


